defmodule BoDatabase.Repo.Migrations.PopulateEntity do
  use Ecto.Migration

  def change do
    BoDatabase.Repo.insert_all(BoDatabase.Entity, [
      # PROTOSS
      [name: "Nexus", img: "building_protoss_nexus"],
        [name: "Sonde", img: "unit_protoss_probe"],
        [name: "Vaisseau mère", img: "unit_protoss_mothership"],
      [name: "Assimilateur", img: "building_protoss_assimilator"],
      [name: "Pylône", img: "building_protoss_pylon"],
      [name: "Portail", img: "building_protoss_gateway"],
        [name: "Zélote", img: "unit_protoss_zealot"],
        [name: "Sentinelle", img: "unit_protoss_sentry"],
        [name: "Traqueur", img: "unit_protoss_stalker"],
        [name: "Adepte", img: "unit_protoss_adept"],
        [name: "Haut templier", img: "unit_protoss_hightemplar"],
        [name: "Templier noir", img: "unit_protoss_darktemplar"],
      [name: "Forge", img: "building_protoss_forge"],
        [name: "Armes terrestres - Niv. 1", img: "upgrade_protoss_groundweaponslevel1"],
        [name: "Armes terrestres - Niv. 2", img: "upgrade_protoss_groundweaponslevel2"],
        [name: "Armes terrestres - Niv. 3", img: "upgrade_protoss_groundweaponslevel3"],
        [name: "Armures terrestres - Niv. 1", img: "upgrade_protoss_groundarmorlevel1"],
        [name: "Armures terrestres - Niv. 2", img: "upgrade_protoss_groundarmorlevel2"],
        [name: "Armures terrestres - Niv. 3", img: "upgrade_protoss_groundarmorlevel3"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel1"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel2"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel3"],
      [name: "Noyau cyberténique", img: "building_protoss_cyberneticscore"],
        [name: "Armes aériennes - Niv. 1", img: "upgrade_protoss_airweaponslevel1"],
        [name: "Armes aériennes - Niv. 2", img: "upgrade_protoss_airweaponslevel2"],
        [name: "Armes aériennes - Niv. 3", img: "upgrade_protoss_airweaponslevel3"],
        [name: "Armures aériennes - Niv. 1", img: "upgrade_protoss_airarmorlevel1"],
        [name: "Armures aériennes - Niv. 2", img: "upgrade_protoss_airarmorlevel2"],
        [name: "Armures aériennes - Niv. 3", img: "upgrade_protoss_airarmorlevel3"],
        [name: "Porte de transfert", img: "building_protoss_warpgate"],
      [name: "Canon à photons", img: "building_protoss_photoncannon"],
      [name: "Batterie de boucliers", img: "building_protoss_shieldbattery"],

      [name: "Conseil crépusculaire", img: "building_protoss_twilightcouncil"],
        [name: "Charge", img: "ability_protoss_charge_color"],
        [name: "Transfert", img: "ability_protoss_blink_color"],
        [name: "Glaives de résonance", img: "ability_protoss_blink_color"],
      [name: "Porte spaciale", img: "building_protoss_stargate"],
        [name: "Phénix", img: "unit_protoss_phoenix"],
        [name: "Oracle", img: "unit_protoss_oracle"],
        [name: "Disloqueur", img: "unit_protoss_warpray"],
        [name: "Tempête", img: "unit_protoss_tempest"],
        [name: "Porte-nefs", img: "unit_protoss_carrier"],
      [name: "Complexe robotique", img: "building_protoss_roboticsfacility"],
        [name: "Observateur", img: "unit_protoss_observer"],
        [name: "Prisme de transfert", img: "unit_protoss_warpprism"],
        [name: "Immortel", img: "unit_protoss_immortal"],
        [name: "Colosse", img: "unit_protoss_colossus"],
        [name: "Disrupteur", img: "unit_protoss_disruptor"],
      [name: "Archive des Templiers", img: "building_protoss_templararchives"],
        [name: "Tempête psionique", img: "ability_protoss_psistorm_color"],
      [name: "Balise de la flotte", img: "building_protoss_fleetbeacon"],
        [name: "Cristaux à impulsion anionique", img: "upgrade_protoss_phoenixrange"],
        [name: "Catapulte à gravitons", img: "upgrade_protoss_gravitoncatapult"],
      [name: "Baie de soutien robotique", img: "building_protoss_roboticssupportbay"],
        [name: "Réacteurs antigrav", img: "upgrade_protoss_graviticbooster"],
        [name: "Répulseur", img: "upgrade_protoss_graviticdrive"],
        [name: "Thermolance étendue", img: "upgrade_protoss_extendedthermallance"],
      [name: "Sanctuaire noir", img: "building_protoss_darkshrine"],
        [name: "Brèche d'ombre", img: "building_protoss_nexus"],

      # TERRAN
      [name: "Centre de commandement", img: "building_terran_commandcenter"],
        [name: "VCS", img: "unit_terran_scv"],
        [name: "Station orbitale", img: "building_terran_surveillancestation"],
        [name: "Forteresse planétaire", img: "building_terran_planetaryfortress"],
      [name: "Raffinerie", img: "building_terran_refinery"],
      [name: "Dépot de ravitaillement", img: "building_terran_supplydepot"],
      [name: "Caserne", img: "building_terran_barracks"],
        [name: "Marine", img: "unit_terran_marine"],
        [name: "Faucheur", img: "unit_terran_reaper"],
        [name: "Maraudeur", img: "unit_terran_marauder"],
        [name: "Fantôme", img: "unit_terran_ghost"],
        [name: "Laboratoire technique caserne", img: "building_terran_techlab"],
          [name: "Bouclier de combat", img: "techupgrade_terran_combatshield_color"],
          [name: "Stimulants", img: "ability_terran_stimpack_color"],
          [name: "Obus incapacitants", img: "ability_terran_punishergrenade_color"],
        [name: "Réacteur caserne", img: "building_terran_reactor"],
      [name: "Centre technique", img: "building_terran_engineeringbay"],
        [name: "Armes infanterie - Niv. 1", img: "upgrade_terran_infantryweaponslevel1"],
        [name: "Armes infanterie - Niv. 2", img: "upgrade_terran_infantryweaponslevel2"],
        [name: "Armes infanterie - Niv. 3", img: "upgrade_terran_infantryweaponslevel3"],
        [name: "Armures infanterie - Niv. 1", img: "upgrade_terran_infantryarmorlevel1"],
        [name: "Armures infanterie - Niv. 2", img: "upgrade_terran_infantryarmorlevel2"],
        [name: "Armures infanterie - Niv. 3", img: "upgrade_terran_infantryarmorlevel3"],
        [name: "Ciblage auto. haute sécurité", img: "upgrade_terran_hisecautotracking"],
        [name: "Structure en NéoAcier", img: "upgrade_terran_neosteelframe"],
        [name: "Blindage bâtiments", img: "upgrade_terran_buildingarmor"],
      [name: "Bunker", img: "building_terran_bunker"],
      [name: "Tourelle lance-missiles", img: "building_terran_missileturret"],
      [name: "Tour de détection", img: "building_terran_sensordome"],

      [name: "Académie fantôme", img: "building_terran_ghostacademy"],
        [name: "Camouflage personnel", img: "ability_terran_cloak_color"],
        [name: "Bombe nucléaire", img: "ability_protoss_blink_color"],
      [name: "Usine", img: "building_terran_factory"],
        [name: "Tourmenteur", img: "unit_terran_hellion"],
        [name: "Mine veuve", img: "unit_terran_widowmine"],
        [name: "Cyclone", img: "unit_terran_cyclone"],
        [name: "Char de siège", img: "unit_terran_siegetank"],
        [name: "Nettoyeur", img: "unit_terran_hellionbattlemode"],
        [name: "Thor", img: "unit_terran_thor"],
        [name: "Laboratoire technique usine", img: "building_terran_techlab"],
          [name: "Amorce infernale", img: "upgrade_terran_infernalpreigniter"],
          [name: "Tirs en rafale", img: "building_protoss_nexus"],
          [name: "Griffes foreuses", img: "upgrade_terran_researchdrillingclaws"],
          [name: "Servoaccélérateurs", img: "building_protoss_nexus"],
        [name: "Réacteur usine", img: "building_terran_reactor"],
      [name: "Armurerie", img: "building_terran_armory"],
        [name: "Armes véhicules - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes véhicules - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes véhicules - Niv. 3", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 3", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 1", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 2", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 3", img: "building_protoss_nexus"],
      [name: "Spatioport", img: "building_terran_starport"],
        [name: "Viking", img: "unit_terran_vikingfighter"],
        [name: "Médivac", img: "unit_terran_dropship"],
        [name: "Croiseur", img: "unit_terran_liberator"],
        [name: "Corbeau", img: "unit_terran_raven"],
        [name: "Banshee", img: "unit_terran_banshee"],
        [name: "Cuirassé", img: "unit_terran_battlecruiser"],
        [name: "Laboratoire technique spatioport", img: "building_terran_techlab"],
          [name: "Réservoirs de haute capacité", img: "upgrade_terran_caduceusreactor"],
          [name: "Réacteur corbin", img: "upgrade_terran_corvidreactor"],
          [name: "Champ de camouflage", img: "ability_terran_cloak_color"],
          [name: "Hyperpropulsion", img: "upgrade_terran_medivacemergencythrusters"],
          [name: "Balistique avancée", img: "upgrade_terran_advanceballistics"],
        [name: "Réacteur spatioport", img: "building_terran_reactor"],
      [name: "Noyau de fusion", img: "building_terran_fusioncore"],
        [name: "Spécialisation", img: "upgrade_terran_behemothreactor"],

      # ZERG
      [name: "Couveuse", img: "building_zerg_hatchery"],
        [name: "Reine", img: "unit_zerg_queen"],
        [name: "Enfouir", img: "building_protoss_nexus"],
        [name: "Carapace pneumatique", img: "building_protoss_nexus"],
        [name: "Terrier", img: "building_zerg_lair"],
          [name: "Ruche", img: "building_zerg_hive"],
      [name: "Extracteur", img: "building_zerg_extractor"],
      [name: "Bassin génétique", img: "building_zerg_spawningpool"],
        [name: "Boost métabolique", img: "upgrade_zerg_metabolicboost"],
        [name: "Glandes surrénales", img: "building_protoss_nexus"],
      [name: "Chambre d'évolution", img: "building_zerg_evolutionchamber"],
        [name: "Attaques de melée - Niv. 1", img: "upgrade_zerg_meleeattacks_level1"],
        [name: "Attaques de melée - Niv. 2", img: "upgrade_zerg_meleeattacks_level2"],
        [name: "Attaques de melée - Niv. 3", img: "upgrade_zerg_meleeattacks_level3"],
        [name: "Attaques à projectiles - Niv. 1", img: "upgrade_zerg_missileattacks_level1"],
        [name: "Attaques à projectiles - Niv. 2", img: "upgrade_zerg_missileattacks_level2"],
        [name: "Attaques à projectiles - Niv. 3", img: "upgrade_zerg_missileattacks_level3"],
        [name: "Carapace terrestre - Niv. 1", img: "upgrade_zerg_groundcarapace_level1"],
        [name: "Carapace terrestre - Niv. 2", img: "upgrade_zerg_groundcarapace_level2"],
        [name: "Carapace terrestre - Niv. 3", img: "upgrade_zerg_groundcarapace_level3"],
      [name: "Terrier de cafards", img: "building_zerg_roachwarren"],
        [name: "Reconstruction gliale", img: "upgrade_zerg_glialreconstitution"],
        [name: "Griffes fouisseuses", img: "building_protoss_nexus"],
      [name: "Nid de Chancres", img: "building_zerg_banelingnest"],
        [name: "Crochets centrifuges", img: "upgrade_zerg_centrifugalhooks"],
      [name: "Aiguillon rampant", img: "building_zerg_spinecrawler"],
      [name: "Sporuleur rampant", img: "building_zerg_sporecrawler"],

      [name: "Tanière d'hydralisks", img: "building_zerg_hydraliskden"],
        [name: "Aiguillons fuselés", img: "upgrade_zerg_groovedspines"],
        [name: "Implants musculaires", img: "building_protoss_nexus"],
      [name: "Fosse d'infestation", img: "building_zerg_infestationpit"],
        [name: "Glandes pathogènes", img: "building_protoss_nexus"],
        [name: "Parasite neural", img: "building_protoss_nexus"],
      [name: "Terrier de rôdeurs", img: "building_zerg_lurkerden"],
        [name: "Griffes falciformes", img: "building_protoss_nexus"],
      [name: "Aiguille", img: "building_zerg_spire"],
        [name: "Attaques volants - Niv. 1", img: "upgrade_zerg_airattacks_level1"],
        [name: "Attaques volants - Niv. 2", img: "upgrade_zerg_airattacks_level2"],
        [name: "Attaques volants - Niv. 3", img: "upgrade_zerg_airattacks_level3"],
        [name: "Carapace volants - Niv. 1", img: "upgrade_zerg_flyercarapace_level1"],
        [name: "Carapace volants - Niv. 2", img: "upgrade_zerg_flyercarapace_level2"],
        [name: "Carapace volants - Niv. 3", img: "upgrade_zerg_flyercarapace_level3"],
        [name: "Grande aiguille", img: "building_zerg_greaterspire"],
      [name: "Réseau de Nydus", img: "building_zerg_nydusnetwork"],
        [name: "Ver de Nydus", img: "building_zerg_nydusworm"],
      [name: "Caverne d'ultralisks", img: "building_zerg_ultraliskcavern"],
        [name: "Armure chitineuse", img: "upgrade_zerg_chitinousplating"],

      [name: "Ouvrier", img: "unit_zerg_drone"],
      [name: "Dominant", img: "unit_zerg_overlord"],
        [name: "Vigilant", img: "unit_zerg_overseer"],
        [name: "Poches ventrales", img: "unit_zerg_overlordtransport"],
      [name: "Zergling", img: "unit_zerg_zergling"],
        [name: "Chancre", img: "unit_zerg_baneling"],
      [name: "Cafard", img: "unit_zerg_roach"],
        [name: "Saccageur", img: "unit_zerg_ravager"],
      [name: "Hydralisk", img: "unit_zerg_hydralisk"],
        [name: "Rôdeur", img: "unit_zerg_lurker"],
      [name: "Mutalisk", img: "unit_zerg_mutalisk"],
      [name: "Corrupteur", img: "unit_zerg_corruptor"],
        [name: "Seigneur-vermine", img: "unit_zerg_broodlord"],
      [name: "Infestateur", img: "unit_zerg_infestor"],
      [name: "Essaimeur", img: "unit_zerg_swarmhost"],
      [name: "Vipère", img: "unit_zerg_viper"],
      [name: "Ultralisk", img: "unit_zerg_ultralisk"]
    ])
  end
end
