defmodule BoDatabase.Repo.Migrations.PopulateEntity do
  use Ecto.Migration

  def change do
    BoDatabase.Repo.insert_all(BoDatabase.Entity, [
      # PROTOSS
      [name: "Nexus", img: "building_protoss_nexus"],
        [name: "Sonde", img: "unit_protoss_probe"],
        [name: "Vaisseau mère", img: "unit_protoss_mothership"],
      [name: "Assimilateur", img: "building_protoss_assimilator"],
      [name: "Pylône", img: "building_protoss_pylon"],
      [name: "Portail", img: "building_protoss_gateway"],
        [name: "Zélote", img: "unit_protoss_zealot"],
        [name: "Sentinelle", img: "unit_protoss_sentry"],
        [name: "Traqueur", img: "unit_protoss_stalker"],
        [name: "Adepte", img: "unit_protoss_adept"],
        [name: "Haut templier", img: "unit_protoss_hightemplar"],
        [name: "Templier noir", img: "unit_protoss_darktemplar"],
      [name: "Forge", img: "building_protoss_forge"],
        [name: "Armes terrestres - Niv. 1", img: "upgrade_protoss_groundweaponslevel1"],
        [name: "Armes terrestres - Niv. 2", img: "upgrade_protoss_groundweaponslevel2"],
        [name: "Armes terrestres - Niv. 3", img: "upgrade_protoss_groundweaponslevel3"],
        [name: "Armures terrestres - Niv. 1", img: "upgrade_protoss_groundarmorlevel1"],
        [name: "Armures terrestres - Niv. 2", img: "upgrade_protoss_groundarmorlevel2"],
        [name: "Armures terrestres - Niv. 3", img: "upgrade_protoss_groundarmorlevel3"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel1"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel2"],
        [name: "Boucliers - Niv. 1", img: "upgrade_protoss_shieldslevel3"],
      [name: "Noyau cyberténique", img: "building_protoss_cyberneticscore"],
        [name: "Armes aériennes - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes aériennes - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes aériennes - Niv. 3", img: "building_protoss_nexus"],
        [name: "Armures aériennes - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armures aériennes - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armures aériennes - Niv. 3", img: "building_protoss_nexus"],
        [name: "Porte de transfert", img: "building_protoss_nexus"],
      [name: "Canon à photons", img: "building_protoss_photoncannon"],
      [name: "Batterie de boucliers", img: "building_protoss_nexus"],

      [name: "Conseil crépusculaire", img: "building_protoss_twilightcouncil"],
        [name: "Charge", img: "ability_protoss_charge_color"],
        [name: "Transfert", img: "ability_protoss_blink_color"],
        [name: "Glaives de résonance", img: "ability_protoss_blink_color"],
      [name: "Porte spaciale", img: "building_protoss_stargate"],
        [name: "Phénix", img: "unit_protoss_phoenix"],
        [name: "Oracle", img: "unit_protoss_oracle"],
        [name: "Disloqueur", img: "unit_protoss_warpray"],
        [name: "Tempête", img: "unit_protoss_tempest"],
        [name: "Porte-nefs", img: "unit_protoss_carrier"],
      [name: "Complexe robotique", img: "building_protoss_roboticsfacility"],
        [name: "Observateur", img: "unit_protoss_observer"],
        [name: "Prisme de transfert", img: "unit_protoss_warpprism"],
        [name: "Immortel", img: "unit_protoss_immortal"],
        [name: "Colosse", img: "unit_protoss_colossus"],
        [name: "Disrupteur", img: "unit_protoss_disruptor"],
      [name: "Archive des Templiers", img: "building_protoss_templararchives"],
        [name: "Tempête psionique", img: "ability_protoss_psistorm_color"],
      [name: "Balise de la flotte", img: "building_protoss_fleetbeacon"],
        [name: "Cristaux à impulsion anionique", img: "upgrade_protoss_phoenixrange"],
        [name: "Catapulte à gravitons", img: "upgrade_protoss_gravitoncatapult"],
      [name: "Baie de soutien robotique", img: "building_protoss_roboticssupportbay"],
        [name: "Réacteurs antigrav", img: "upgrade_protoss_graviticbooster"],
        [name: "Répulseur", img: "upgrade_protoss_graviticdrive"],
        [name: "Thermolance étendue", img: "upgrade_protoss_extendedthermallance"],
      [name: "Sanctuaire noir", img: "building_protoss_darkshrine"],
        [name: "Brèche d'ombre", img: "building_protoss_nexus"],

      # TERRAN
      [name: "Centre de commandement", img: "building_protoss_nexus"],
        [name: "VCS", img: "building_protoss_nexus"],
        [name: "Station orbitale", img: "building_protoss_nexus"],
        [name: "Forteresse planétaire", img: "building_protoss_nexus"],
      [name: "Raffinerie", img: "building_protoss_nexus"],
      [name: "Dépot de ravitaillement", img: "building_protoss_nexus"],
      [name: "Caserne", img: "building_protoss_nexus"],
        [name: "Marine", img: "building_protoss_nexus"],
        [name: "Faucheur", img: "building_protoss_nexus"],
        [name: "Maraudeur", img: "building_protoss_nexus"],
        [name: "Fantôme", img: "building_protoss_nexus"],
        [name: "Laboratoire technique caserne", img: "building_protoss_nexus"],
          [name: "Bouclier de combat", img: "building_protoss_nexus"],
          [name: "Stimulants", img: "building_protoss_nexus"],
          [name: "Obus incapacitants", img: "building_protoss_nexus"],
        [name: "Réacteur caserne", img: "building_protoss_nexus"],
      [name: "Centre technique", img: "building_protoss_nexus"],
        [name: "Armes infanterie - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes infanterie - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes infanterie - Niv. 3", img: "building_protoss_nexus"],
        [name: "Armures infanterie - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armures infanterie - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armures infanterie - Niv. 3", img: "building_protoss_nexus"],
        [name: "Ciblage auto. haute sécurité", img: "building_protoss_nexus"],
        [name: "Structure en NéoAcier", img: "building_protoss_nexus"],
        [name: "Blindage bâtiments", img: "building_protoss_nexus"],
      [name: "Bunker", img: "building_protoss_nexus"],
      [name: "Tourelle lance-missiles", img: "building_protoss_nexus"],
      [name: "Tour de détection", img: "building_protoss_nexus"],

      [name: "Académie fantôme", img: "building_protoss_nexus"],
        [name: "Camouflage personnel", img: "ability_protoss_charge_color"],
        [name: "Bombe nucléaire", img: "ability_protoss_blink_color"],
      [name: "Usine", img: "building_protoss_nexus"],
        [name: "Tourmenteur", img: "building_protoss_nexus"],
        [name: "Mine veuve", img: "building_protoss_nexus"],
        [name: "Cyclone", img: "building_protoss_nexus"],
        [name: "Char de siège", img: "building_protoss_nexus"],
        [name: "Nettoyeur", img: "building_protoss_nexus"],
        [name: "Thor", img: "building_protoss_nexus"],
        [name: "Laboratoire technique usine", img: "building_protoss_nexus"],
          [name: "Amorce infernale", img: "building_protoss_nexus"],
          [name: "Tirs en rafale", img: "building_protoss_nexus"],
          [name: "Griffes foreuses", img: "building_protoss_nexus"],
          [name: "Servoaccélérateurs", img: "building_protoss_nexus"],
        [name: "Réacteur usine", img: "building_protoss_nexus"],
      [name: "Armurerie", img: "building_protoss_nexus"],
        [name: "Armes véhicules - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes véhicules - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes véhicules - Niv. 3", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 1", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 2", img: "building_protoss_nexus"],
        [name: "Armes vaisseau - Niv. 3", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 1", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 2", img: "building_protoss_nexus"],
        [name: "Blindage véhicule et vaisseau - Niv. 3", img: "building_protoss_nexus"],
      [name: "Spatioport", img: "building_protoss_nexus"],
        [name: "Viking", img: "building_protoss_nexus"],
        [name: "Médivac", img: "building_protoss_nexus"],
        [name: "Croiseur", img: "building_protoss_nexus"],
        [name: "Corbeau", img: "building_protoss_nexus"],
        [name: "Banshee", img: "building_protoss_nexus"],
        [name: "Cuirassé", img: "building_protoss_nexus"],
        [name: "Laboratoire technique spatioport", img: "building_protoss_nexus"],
          [name: "Réservoirs de haute capacité", img: "building_protoss_nexus"],
          [name: "Réacteur corbin", img: "building_protoss_nexus"],
          [name: "Champ de camouflage", img: "building_protoss_nexus"],
          [name: "Hyperpropulsion", img: "building_protoss_nexus"],
          [name: "Balistique avancée", img: "building_protoss_nexus"],
        [name: "Réacteur spatioport", img: "building_protoss_nexus"],
      [name: "Noyau de fusion", img: "building_protoss_nexus"],
        [name: "Spécialisation", img: "building_protoss_nexus"],

      # ZERG
      [name: "Couveuse", img: "building_protoss_nexus"],
        [name: "Reine", img: "building_protoss_nexus"],
        [name: "Enfouir", img: "building_protoss_nexus"],
        [name: "Carapace pneumatique", img: "building_protoss_nexus"],
        [name: "Terrier", img: "building_protoss_nexus"],
          [name: "Ruche", img: "building_protoss_nexus"],
      [name: "Extracteur", img: "building_protoss_nexus"],
      [name: "Bassin génétique", img: "building_protoss_nexus"],
        [name: "Boost métabolique", img: "building_protoss_nexus"],
        [name: "Glandes surrénales", img: "building_protoss_nexus"],
      [name: "Chambre d'évolution", img: "building_protoss_nexus"],
        [name: "Attaques de melée - Niv. 1", img: "building_protoss_nexus"],
        [name: "Attaques de melée - Niv. 2", img: "building_protoss_nexus"],
        [name: "Attaques de melée - Niv. 3", img: "building_protoss_nexus"],
        [name: "Attaques à projectiles - Niv. 1", img: "building_protoss_nexus"],
        [name: "Attaques à projectiles - Niv. 2", img: "building_protoss_nexus"],
        [name: "Attaques à projectiles - Niv. 3", img: "building_protoss_nexus"],
        [name: "Carapace terrestre - Niv. 1", img: "building_protoss_nexus"],
        [name: "Carapace terrestre - Niv. 2", img: "building_protoss_nexus"],
        [name: "Carapace terrestre - Niv. 3", img: "building_protoss_nexus"],
      [name: "Terrier de cafards", img: "building_protoss_nexus"],
        [name: "Reconstruction gliale", img: "building_protoss_nexus"],
        [name: "Griffes fouisseuses", img: "building_protoss_nexus"],
      [name: "Nid de Chancres", img: "building_protoss_nexus"],
        [name: "Crochets centrifuges", img: "building_protoss_nexus"],
      [name: "Aiguillon rampant", img: "building_protoss_nexus"],
      [name: "Sporuleur rampant", img: "building_protoss_nexus"],

      [name: "Tanière d'hydralisks", img: "building_protoss_nexus"],
        [name: "Aiguillons fuselés", img: "building_protoss_nexus"],
        [name: "Implants musculaires", img: "building_protoss_nexus"],
      [name: "Fosse d'infestation", img: "building_protoss_nexus"],
        [name: "Glandes pathogènes", img: "building_protoss_nexus"],
        [name: "Parasite neural", img: "building_protoss_nexus"],
      [name: "Terrier de rôdeurs", img: "building_protoss_nexus"],
        [name: "Griffes falciformes", img: "building_protoss_nexus"],
      [name: "Aiguille", img: "building_protoss_nexus"],
        [name: "Attaques volants - Niv. 1", img: "building_protoss_nexus"],
        [name: "Attaques volants - Niv. 2", img: "building_protoss_nexus"],
        [name: "Attaques volants - Niv. 3", img: "building_protoss_nexus"],
        [name: "Carapace volants - Niv. 1", img: "building_protoss_nexus"],
        [name: "Carapace volants - Niv. 2", img: "building_protoss_nexus"],
        [name: "Carapace volants - Niv. 3", img: "building_protoss_nexus"],
        [name: "Grande aiguille - Niv. 3", img: "building_protoss_nexus"],
      [name: "Réseau de Nydus", img: "building_protoss_nexus"],
        [name: "Ver de Nydus", img: "building_protoss_nexus"],
      [name: "Caverne d'ultralisks", img: "building_protoss_nexus"],
        [name: "Armure chitineuse", img: "building_protoss_nexus"],

      [name: "Ouvrier", img: "building_protoss_nexus"],
      [name: "Dominant", img: "building_protoss_nexus"],
        [name: "Vigilant", img: "building_protoss_nexus"],
        [name: "Poches ventrales", img: "building_protoss_nexus"],
      [name: "Zergling", img: "building_protoss_nexus"],
        [name: "Chancre", img: "building_protoss_nexus"],
      [name: "Cafard", img: "building_protoss_nexus"],
        [name: "Saccageur", img: "building_protoss_nexus"],
      [name: "Hydralisk", img: "building_protoss_nexus"],
        [name: "Rôdeur", img: "building_protoss_nexus"],
      [name: "Mutalisk", img: "building_protoss_nexus"],
      [name: "Corrupteur", img: "building_protoss_nexus"],
        [name: "Seigneur-vermine", img: "building_protoss_nexus"],
      [name: "Infestateur", img: "building_protoss_nexus"],
      [name: "Essaimeur", img: "building_protoss_nexus"],
      [name: "Vipère", img: "building_protoss_nexus"],
      [name: "Ultralisk", img: "building_protoss_nexus"]
    ])
  end
end
